In [81]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [82]:
pizza=pd.read_csv(r'..\Datasets\pizza.csv')
pizza.head()

Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [83]:
train,test =train_test_split(pizza,test_size=0.3,random_state=25)

In [84]:
s1=train.sample(n=train.shape[0],replace=True,random_state=25)
s2=train.sample(n=train.shape[0],replace=True,random_state=25)
s3=train.sample(n=train.shape[0],replace=True,random_state=25)


In [85]:
lr1,lr2,lr3=LinearRegression(),LinearRegression(),LinearRegression()
X_test,y_test=test[['Promote']],test[['Sales']]

In [86]:
X_train,y_train=s1[['Promote']],s1[['Sales']]
lr1.fit(X_train,y_train)
lr1.predict(X_test)


array([[1266.34589485],
       [2196.16639138],
       [ 336.52539832],
       [1608.91134094],
       [1119.53213224],
       [ 556.74604223]])

In [87]:
X_train,y_train=s2[['Promote']],s2[['Sales']]
lr2.fit(X_train,y_train)
lr2.predict(X_test)

array([[1266.34589485],
       [2196.16639138],
       [ 336.52539832],
       [1608.91134094],
       [1119.53213224],
       [ 556.74604223]])

In [88]:
X_train,y_train=s3[['Promote']],s3[['Sales']]
lr3.fit(X_train,y_train)
lr3.predict(X_test)

array([[1266.34589485],
       [2196.16639138],
       [ 336.52539832],
       [1608.91134094],
       [1119.53213224],
       [ 556.74604223]])

In [89]:
np.random.seed(25)
list(pizza.index)
sample=np.random.choice(list(pizza.index),100,replace=True)
sample

array([ 4, 15, 12, 18,  8,  4,  5,  1,  7,  3,  3, 13,  3,  1, 16, 15,  9,
       16, 12, 13, 18,  4,  9,  0, 10, 15, 10,  1, 17, 18,  4,  2,  5,  8,
       11, 16,  6,  2,  5,  9, 16, 11,  2, 11, 10, 17, 14,  5, 10, 18, 14,
        7, 15, 14, 12,  7, 14,  5, 13, 14,  3,  2, 12, 12, 13,  9,  3, 15,
        0,  5,  4, 14, 11,  5,  2, 17, 12,  7, 18, 14,  1, 10,  3,  8,  0,
       16,  3, 16, 16, 12,  4,  0,  7, 18,  0,  0,  5,  3,  0, 14])

In [90]:
pizza.iloc[sample,:]

Promote  Sales
4        67   1600
15       44   1000
12       71   1750
18       22    550
8         6    150
..      ...    ...
0        23    554
5        82   2000
3        25    609
0        23    554
14       66   1500

[100 rows x 2 columns]

Bootstrping using `sklearn`

In [ ]:
from sklearn.ensemble import BaggingRegressor

In [92]:
lr=LinearRegression()
bagg=BaggingRegressor(estimator=lr,n_estimators=10)

In [93]:
x,y=pizza[['Promote']],pizza['Sales']
X_train,X_test,y_train,y_test =train_test_split(x,y,test_size=0.3,random_state=25)

In [94]:
from sklearn.metrics import r2_score
bagg.fit(X_train,y_train)
y_pred=bagg.predict(X_test)
print(r2_score(y_test,y_pred))

0.9742773587746619


Individual estimator performance

In [95]:
lr.fit(X_train,y_train)

LinearRegression()