In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import os
from sklearn.preprocessing import LabelEncoder

In [22]:
test_house = pd.read_csv(r'..\Datasets\tst_Housing.csv')
house_df = pd.read_csv(r'..\Datasets\Housing.csv')
test_house.head()
house_df.head()

price  lotsize  bedrooms  bathrms  stories driveway recroom fullbase  \
0  42000.0     5850         3        1        2      yes      no      yes   
1  38500.0     4000         2        1        1      yes      no       no   
2  49500.0     3060         3        1        1      yes      no       no   
3  60500.0     6650         3        1        2      yes     yes       no   
4  61000.0     6360         2        1        1      yes      no       no   

  gashw airco  garagepl prefarea  
0    no    no         1       no  
1    no    no         0       no  
2    no    no         0       no  
3    no    no         0       no  
4    no    no         0       no

In [23]:
le=LabelEncoder()
house_df['driveway'] = le.fit_transform(house_df['driveway'])
house_df['recroom'] = le.fit_transform(house_df['recroom'])
house_df['fullbase'] = le.fit_transform(house_df['fullbase'])
house_df['gashw'] = le.fit_transform(house_df['gashw'])
house_df['prefarea'] = le.fit_transform(house_df['prefarea'])
house_df['airco'] = le.fit_transform(house_df['airco'])
house_df.head()



price  lotsize  bedrooms  bathrms  stories  driveway  recroom  fullbase  \
0  42000.0     5850         3        1        2         1        0         1   
1  38500.0     4000         2        1        1         1        0         0   
2  49500.0     3060         3        1        1         1        0         0   
3  60500.0     6650         3        1        2         1        1         0   
4  61000.0     6360         2        1        1         1        0         0   

   gashw  airco  garagepl  prefarea  
0      0      0         1         0  
1      0      0         0         0  
2      0      0         0         0  
3      0      0         0         0  
4      0      0         0         0

In [24]:
sc=StandardScaler()
sc.fit_transform(house_df.drop('price',axis=1))


array([[ 0.32302806,  0.0472349 , -0.5694948 , ..., -0.68103375,
         0.35756661, -0.55337157],
       [-0.53101296, -1.31014696, -0.5694948 , ..., -0.68103375,
        -0.80452487, -0.55337157],
       [-0.96495812,  0.0472349 , -0.5694948 , ..., -0.68103375,
        -0.80452487, -0.55337157],
       ...,
       [ 0.39227462,  0.0472349 ,  1.42373699, ...,  1.46835601,
         0.35756661, -0.55337157],
       [ 0.39227462,  0.0472349 ,  1.42373699, ...,  1.46835601,
         0.35756661, -0.55337157],
       [ 0.39227462,  0.0472349 , -0.5694948 , ...,  1.46835601,
         0.35756661, -0.55337157]])

In [25]:
x , y = house_df.drop(['price'],axis=1), house_df['price']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=25)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((382, 11), (164, 11), (382,), (164,))

In [26]:
from sklearn.linear_model import Ridge
alpha_set=[0.001,0.01,0.1,1,2]
# 0.001 is the alpha value which is the regularization parameter
for i in alpha_set:
    ridge=Ridge(alpha=i)
    ridge.fit(x_train,y_train)
    y_pred = ridge.predict(x_test)
    print("\nalpha",i)
    print("mean_absolute_error",mean_absolute_error(y_test, y_pred))
    print("mean_squared_error",mean_squared_error(y_test, y_pred))
    print("r2_score",r2_score(y_test, y_pred))


alpha 0.001
mean_absolute_error 11600.919546985773
mean_squared_error 272723459.9691819
r2_score 0.635589108852145

alpha 0.01
mean_absolute_error 11600.720198067615
mean_squared_error 272714361.19644994
r2_score 0.6356012665590031

alpha 0.1
mean_absolute_error 11598.73439365131
mean_squared_error 272624530.96295494
r2_score 0.6357212969936552

alpha 1
mean_absolute_error 11581.329164693385
mean_squared_error 271833299.4321408
r2_score 0.636778534193861

alpha 2
mean_absolute_error 11567.891078207322
mean_squared_error 271150728.60364616
r2_score 0.6376905798386008


In [27]:
from sklearn.linear_model import Lasso
alpha_set=[0.001,0.01,0.1,1,2]
# 0.001 is the alpha value which is the regularization parameter
for i in alpha_set:
    ridge=Lasso(alpha=i)
    ridge.fit(x_train,y_train)
    y_pred = ridge.predict(x_test)
    print("\nalpha",i)
    print("mean_absolute_error",mean_absolute_error(y_test, y_pred))
    print("mean_squared_error",mean_squared_error(y_test, y_pred))
    print("r2_score",r2_score(y_test, y_pred))


alpha 0.001
mean_absolute_error 11600.94106922149
mean_squared_error 272724464.77582467
r2_score 0.6355877662375999

alpha 0.01
mean_absolute_error 11600.93534238882
mean_squared_error 272724397.4832146
r2_score 0.6355878561534438

alpha 0.1
mean_absolute_error 11600.878074100123
mean_squared_error 272723725.2320205
r2_score 0.635588754410076

alpha 1
mean_absolute_error 11600.305296671579
mean_squared_error 272717054.3322119
r2_score 0.6355976680126839

alpha 2
mean_absolute_error 11599.668300714626
mean_squared_error 272709775.9621113
r2_score 0.6356073933122044


In [30]:
#Elastic net regression
from sklearn.linear_model import ElasticNet

#Testing different alpha values and l1_ratio values to find the best combination.
ration=[0.01,0.25,0.5,0.75,0.9]
alpha_set=[0.001,0.01,0.1,0.5,1,2] 
scores=[]
for i in alpha_set:
    for j in ration:
        el=ElasticNet(alpha=i, l1_ratio=j,random_state=25)
        el.fit(x_train,y_train)
        y_pred = el.predict(x_test)
        scores.append([j,i,r2_score(y_test, y_pred)])
scores=pd.DataFrame(scores, columns=['ratio','alpha','r2_score'])
scores.sort_values(by='r2_score', ascending=False).head(10)

ratio  alpha  r2_score
13   0.75  0.100  0.639500
14   0.90  0.100  0.638804
5    0.01  0.010  0.638787
6    0.25  0.010  0.638297
7    0.50  0.010  0.637618
8    0.75  0.010  0.636731
12   0.50  0.100  0.636281
19   0.90  0.500  0.636264
9    0.90  0.010  0.636080
0    0.01  0.001  0.636075

In [32]:
test_house.head()

lotsize  bedrooms  bathrms  stories driveway recroom fullbase gashw airco  \
0     5600         3        1        2      yes      no      yes    no    no   
1     4355         2        1        1      yes      no       no    no    no   
2     3412         3        1        1      yes      no       no    no    no   
3     6666         2        2        2      yes     yes       no    no    no   

   garagepl prefarea  
0         1       no  
1         0       no  
2         0       no  
3         0       no

In [38]:
le=LabelEncoder()
test_house['driveway'] = le.fit_transform(test_house['driveway'])
test_house['recroom'] = le.fit_transform(test_house['recroom'])
test_house['fullbase'] = le.fit_transform(test_house['fullbase'])
test_house['gashw'] = le.fit_transform(test_house['gashw'])
test_house['prefarea'] = le.fit_transform(test_house['prefarea'])
test_house['airco'] = le.fit_transform(test_house['airco'])
test_house.head()

sc=StandardScaler()
sc.fit_transform(test_house)



array([[ 0.48024708,  1.        , -0.57735027,  1.        ,  0.        ,
        -0.57735027,  1.73205081,  0.        ,  0.        ,  1.73205081,
         0.        ],
       [-0.53015869, -1.        , -0.57735027, -1.        ,  0.        ,
        -0.57735027, -0.57735027,  0.        ,  0.        , -0.57735027,
         0.        ],
       [-1.29547006,  1.        , -0.57735027, -1.        ,  0.        ,
        -0.57735027, -0.57735027,  0.        ,  0.        , -0.57735027,
         0.        ],
       [ 1.34538167, -1.        ,  1.73205081,  1.        ,  0.        ,
         1.73205081, -0.57735027,  0.        ,  0.        , -0.57735027,
         0.        ]])

In [43]:

el=ElasticNet(alpha=0.75, l1_ratio=1,random_state=25)
el.fit(x_train,y_train)
y_pred = el.predict(test_house)
y_pred


array([56568.33654519, 36147.45196503, 33243.83095678, 70422.03459151])